### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by AntonOfTheWoods** [atroo/rxstorage-indexeddb#1]
It would be nice to get some idea of the project via a readme, to know at least how it is situated wrt RxDB, the new dexie adapter, etc.

**Comment by phal0r** [comment]
Hi @AntonOfTheWoods ,

yeah, we will definitely add a README as it's already on our ToDo-List. We need this Storage for the web version for one of our projects and we just released version 1.0.1 to move forward. We did integrate the Storage into the app and are validating it right now.

When releasing RxDB 10 pubkey, that he did not intend to write storages on his own and we needed a way to get away from the pouch ecosystem as we only rely on graphql. This is how it started.

**Comment by AntonOfTheWoods** [comment]
Thanks @phal0r , I was particularly interested in whether there might be value in eventually merging this with the `dexie` storage, as performance would probably be very similar, and there might not be much value in having both. Have you guys discussed that since the appearance of the dexie version?

**Comment by phal0r** [comment]
yeah, there was a discussion and I agree about merging. However, there is no specific plan yet on how this could work.

**Comment by AntonOfTheWoods** [comment]
Perfect, thanks for the info and the readme! I'll take it out for a spin :->

**Comment by aehlke** [comment]
Has this worked well in prod? Is it good to use over Dexie.js still? Thank you

**Comment by phal0r** [comment]
Hi @aehlke 

thanks for reaching out. We created this storage at a time, when there were no storages available from rxdb itself. This has changed drastically and you should definitely take those as this storage here is not maintained. I will set the repo to archived, so it is clear for everyone.
